#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
STATE_FILE="${SCRIPT_DIR}/.wg-vpn.state"
ENV_VARS=(
    WG_CONFIG_DIR
    WG_CONFIG_FILE
)
DEPENDENCIES=(
    "nmcli"
    "ufw"
    "sudo"
    "ip"
)
PRIVATE_SUBNETS=(
    "10.0.0.0/8"
    "172.16.0.0/12"
    "192.168.0.0/16"
)
ENTRYPOINT_LOADED="true"

# Source scripts
. "$SCRIPT_DIR/lib/core.sh"
. "$SCRIPT_DIR/lib/routers.sh"
. "$SCRIPT_DIR/lib/commands/misc.sh"
. "$SCRIPT_DIR/lib/commands/toggle-vpn.sh"

# Main
first_arg="${1:-}"
shift || true
process_command "$first_arg"
