#!/usr/bin/env bash
set -euo pipefail

if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 3))); then
    echo "Error: This script requires Bash 4.3 or higher." >&2
    exit 1
fi

LIB_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/lib"

# XDG base dir paths
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/wg-vpn"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/wg-vpn"

CONFIG_FILE="${CONFIG_DIR}/wg-vpn.conf"
SUBNETS_FILE="${CONFIG_DIR}/subnets.list"
STATE_FILE="${STATE_DIR}/wg-vpn.state"
LOCK_FILE="${STATE_DIR}/wg-vpn.lock"
LOCK_ACQUIRED=0

declare -A ENV_VARS=(
    [WG_CONFIG_DIR]="Wireguard config directory (e.g., /etc/wireguard/)"
    [WG_CONFIG_FILE]="default config file (e.g., us1.conf)"
)
DEPENDENCIES=(
    "nmcli"
    "ufw"
    "sudo"
    "ip"
    "flock"
)
ENTRYPOINT_LOADED="true"

# Source scripts

# shellcheck source=lib/core.sh
. "$LIB_DIR/core.sh"

# shellcheck source=lib/routers.sh
. "$LIB_DIR/routers.sh"

# shellcheck source=lib/commands/misc.sh
. "$LIB_DIR/commands/misc.sh"

# shellcheck source=lib/commands/toggle-vpn.sh
. "$LIB_DIR/commands/toggle-vpn.sh"

# Main
first_arg="${1:-}"
shift || true
process_command "$first_arg"
