#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# XDG base dir paths
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/wg-vpn"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/wg-vpn"

CONFIG_FILE="${CONFIG_DIR}/wg-vpn.conf"
STATE_FILE="${STATE_DIR}/wg-vpn.state"

declare -A ENV_VARS=(
    [WG_CONFIG_DIR]="Wireguard config directory (e.g., /etc/wireguard/)"
    [WG_CONFIG_FILE]="default config file (e.g., us1.conf)"
)
DEPENDENCIES=(
    "nmcli"
    "ufw"
    "sudo"
    "ip"
)
ENTRYPOINT_LOADED="true"

# Source scripts
. "$SCRIPT_DIR/lib/core.sh"
. "$SCRIPT_DIR/lib/routers.sh"
. "$SCRIPT_DIR/lib/commands/misc.sh"
. "$SCRIPT_DIR/lib/commands/toggle-vpn.sh"

# Main
first_arg="${1:-}"
shift || true
process_command "$first_arg"
